apiVersion: v1
kind: ConfigMap
metadata:
  name: urlshortner-config
  namespace: urlshortner
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  GO_SERVICE_URL: "http://go-service.urlshortner.svc.cluster.local:8000"
  NODE_SERVICE_URL: "http://node-service.urlshortner.svc.cluster.local:3000"

---
apiVersion: v1
kind: Secret
metadata:
  name: urlshortner-secret
  namespace: urlshortner
type: Opaque
stringData:
  FLASK_SECRET_KEY: "change-me"
