apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-service
  namespace: urlshortner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-service
  template:
    metadata:
      labels:
        app: node-service
    spec:
      containers:
        - name: node-service
          image: shodeitanim/urlshortner-node:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: urlshortner-config
            - secretRef:
                name: urlshortner-secret
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: urlshortner
spec:
  selector:
    app: node-service
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
