apiVersion: v1
kind: Service
metadata:
  name: python-lb
  namespace: urlshortner
spec:
  type: NodePort
  selector:
    app: python-service
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
