name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Go service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./go-service/Dockerfile
          push: true
          tags: xaadu/urlshortner-go:latest

      - name: Build and push Python service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./python-service/Dockerfile
          push: true
          tags: xaadu/urlshortner-python:latest

      - name: Build and push Node service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./node-service/Dockerfile
          push: true
          tags: xaadu/urlshortner-node:latest
